-- AlterTable
ALTER TABLE "posts" ADD COLUMN     "costOfLivingScore" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "finalScore" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "greenAreasScore" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "mainAddress" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "mainAddressLat" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "mainAddressLng" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "pollutionScore" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "qualityOfLifeScore" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "securityScore" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "transportationScore" DOUBLE PRECISION DEFAULT 0,
ALTER COLUMN "avgRentPerSqM" SET DEFAULT 0,
ALTER COLUMN "avgSalePerSqM" SET DEFAULT 0;
